### PR TITLE
GCAM to Demeter: agricultural production xml query

### PR DESCRIPTION
**Pull request by crvernon**
**GCAM to Demeter: agricultural production by technology xml query**

**GCAM-USA version**:  5.3 (IM3 version)

**Expected agricultural production for forest units from GCAM**:  billion m3<sup>3</sup>

**Expected fields**:  

| field_name | data_type | description | 
| ----------- | ---------- | ------------ | 
|`Units` | str | GCAM units| 
| `scenario` | str | GCAM scenario name | 
| `region` | str | GCAM geopolitical region | 
| `sector` | str | GCAM agriculture sector (e.g., `biomass`) | 
| `subsector` | str | GCAM agriculture sector combined with the basin abbreviation (e.g., `biomassGrass_AfrCstE`) | 
| `technology` | str | GCAM agriculture subsector combined with irrigation and management status  (e.g., `biomassGrass_AfrCstE_IRR_hi `) | 
| `output` | str | Same as GCAM agriculture sector (e.g., `biomass`) | 
| `Year` | int | GCAM year |
| `value` | float | value in native units | 

**Meta-Issue**:  #1

### CODE REVIEW

**Review by pralitp — APPROVED** [review]
This query likely seems sufficient to me.  A couple of notes just in case:
1. This will get primary production, i.e. no residue biomass results.  I think that is what we want for this use case but just noting it.
2. The query isn't controlling for any crop naming conventions so we will need to be prepared for v5.3 naming on the Demeter side.

**Comment by kanishkan91** [comment]
@pralitp This query is required from demeter only to get wood production. I was just going to filter for forest techs from these.

**Comment by crvernon** [comment]
@kanishkan91 do you approve this one or is there more to flesh out here?

**Review by kanishkan91 — APPROVED** [review]
Approved

**Pull request merged**
